# Generated by Django 5.1.1 on 2025-07-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_productimage_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcategory',
            new_name='Subcategories',
        ),
    ]
