# Generated by Django 5.1.1 on 2025-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_subcategory_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategories',
            name='parent_category',
        ),
        migrations.AddField(
            model_name='subcategories',
            name='parent_category',
            field=models.ManyToManyField(related_name='subcategories', to='shop.category'),
        ),
    ]
